# Generated by Django 4.0.3 on 2023-05-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('compileted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
