# Generated by Django 4.0.3 on 2023-05-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_task_id_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='id',
            new_name='task_id',
        ),
    ]
